// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package message

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindUnknown-0]
	_ = x[KindAppendEntriesRequest-1]
	_ = x[KindAppendEntriesResponse-2]
	_ = x[KindFollowerLocationListRequest-3]
	_ = x[KindFollowerLocationListResponse-4]
	_ = x[KindLeaderLocationRequest-5]
	_ = x[KindLeaderLocationResponse-6]
	_ = x[KindRequestVoteRequest-7]
	_ = x[KindRequestVoteResponse-8]
}

const _Kind_name = "KindUnknownKindAppendEntriesRequestKindAppendEntriesResponseKindFollowerLocationListRequestKindFollowerLocationListResponseKindLeaderLocationRequestKindLeaderLocationResponseKindRequestVoteRequestKindRequestVoteResponse"

var _Kind_index = [...]uint8{0, 11, 35, 60, 91, 123, 148, 174, 196, 219}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
