// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: leader_location.proto

//lint:file-ignore SA1019 Generated deprecated import

package message

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LeaderLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LeaderLocationRequest) Reset() {
	*x = LeaderLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leader_location_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderLocationRequest) ProtoMessage() {}

func (x *LeaderLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leader_location_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderLocationRequest.ProtoReflect.Descriptor instead.
func (*LeaderLocationRequest) Descriptor() ([]byte, []int) {
	return file_leader_location_proto_rawDescGZIP(), []int{0}
}

type LeaderLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaderAddress string `protobuf:"bytes,1,opt,name=leaderAddress,proto3" json:"leaderAddress,omitempty"`
}

func (x *LeaderLocationResponse) Reset() {
	*x = LeaderLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leader_location_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderLocationResponse) ProtoMessage() {}

func (x *LeaderLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leader_location_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderLocationResponse.ProtoReflect.Descriptor instead.
func (*LeaderLocationResponse) Descriptor() ([]byte, []int) {
	return file_leader_location_proto_rawDescGZIP(), []int{1}
}

func (x *LeaderLocationResponse) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

var File_leader_location_proto protoreflect.FileDescriptor

var file_leader_location_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x17, 0x0a, 0x15, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x16, 0x4c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_leader_location_proto_rawDescOnce sync.Once
	file_leader_location_proto_rawDescData = file_leader_location_proto_rawDesc
)

func file_leader_location_proto_rawDescGZIP() []byte {
	file_leader_location_proto_rawDescOnce.Do(func() {
		file_leader_location_proto_rawDescData = protoimpl.X.CompressGZIP(file_leader_location_proto_rawDescData)
	})
	return file_leader_location_proto_rawDescData
}

var file_leader_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_leader_location_proto_goTypes = []interface{}{
	(*LeaderLocationRequest)(nil),  // 0: message.LeaderLocationRequest
	(*LeaderLocationResponse)(nil), // 1: message.LeaderLocationResponse
}
var file_leader_location_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_leader_location_proto_init() }
func file_leader_location_proto_init() {
	if File_leader_location_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_leader_location_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leader_location_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_leader_location_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_leader_location_proto_goTypes,
		DependencyIndexes: file_leader_location_proto_depIdxs,
		MessageInfos:      file_leader_location_proto_msgTypes,
	}.Build()
	File_leader_location_proto = out.File
	file_leader_location_proto_rawDesc = nil
	file_leader_location_proto_goTypes = nil
	file_leader_location_proto_depIdxs = nil
}
