// Code generated by "stringer -type=step"; DO NOT EDIT.

package lbadd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stepInit-0]
	_ = x[stepSelectField-1]
	_ = x[stepSelectComma-2]
	_ = x[stepSelectFrom-3]
	_ = x[stepSelectTable-4]
}

const _step_name = "stepInitstepSelectFieldstepSelectCommastepSelectFromstepSelectTable"

var _step_index = [...]uint8{0, 8, 23, 38, 52, 67}

func (i step) String() string {
	if i < 0 || i >= step(len(_step_index)-1) {
		return "step(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _step_name[_step_index[i]:_step_index[i+1]]
}
