// Code generated by "stringer -type=TypeIndicator"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeIndicatorUnknown-0]
	_ = x[TypeIndicatorBool-1]
	_ = x[TypeIndicatorDate-2]
	_ = x[TypeIndicatorInteger-3]
	_ = x[TypeIndicatorReal-4]
	_ = x[TypeIndicatorString-5]
}

const _TypeIndicator_name = "TypeIndicatorUnknownTypeIndicatorBoolTypeIndicatorDateTypeIndicatorIntegerTypeIndicatorRealTypeIndicatorString"

var _TypeIndicator_index = [...]uint8{0, 20, 37, 54, 74, 91, 110}

func (i TypeIndicator) String() string {
	if i >= TypeIndicator(len(_TypeIndicator_index)-1) {
		return "TypeIndicator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeIndicator_name[_TypeIndicator_index[i]:_TypeIndicator_index[i+1]]
}
