// Code generated by "stringer -type=DeltaType"; DO NOT EDIT.

package cmp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Nilness-1]
	_ = x[TokenValue-2]
	_ = x[TokenPosition-3]
}

const _DeltaType_name = "UnknownNilnessTokenValueTokenPosition"

var _DeltaType_index = [...]uint8{0, 7, 14, 24, 37}

func (i DeltaType) String() string {
	if i >= DeltaType(len(_DeltaType_index)-1) {
		return "DeltaType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeltaType_name[_DeltaType_index[i]:_DeltaType_index[i+1]]
}
