// Code generated by "stringer -type=BaseType"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BaseTypeUnknown-0]
	_ = x[BaseTypeBool-1]
	_ = x[BaseTypeBinary-2]
	_ = x[BaseTypeString-3]
	_ = x[BaseTypeNumber-4]
}

const _BaseType_name = "BaseTypeUnknownBaseTypeBoolBaseTypeBinaryBaseTypeStringBaseTypeNumber"

var _BaseType_index = [...]uint8{0, 15, 27, 41, 55, 69}

func (i BaseType) String() string {
	if i >= BaseType(len(_BaseType_index)-1) {
		return "BaseType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BaseType_name[_BaseType_index[i]:_BaseType_index[i+1]]
}
