// Code generated by "stringer -type=cmpResult"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[cmpUncomparable-0]
	_ = x[cmpEqual-1]
	_ = x[cmpLessThan-2]
	_ = x[cmpGreaterThan-3]
}

const _cmpResult_name = "cmpUncomparablecmpEqualcmpLessThancmpGreaterThan"

var _cmpResult_index = [...]uint8{0, 15, 23, 34, 48}

func (i cmpResult) String() string {
	if i >= cmpResult(len(_cmpResult_index)-1) {
		return "cmpResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _cmpResult_name[_cmpResult_index[i]:_cmpResult_index[i+1]]
}
