// Code generated by "stringer -type=BaseType"; DO NOT EDIT.

package column

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Decimal-1]
	_ = x[Varchar-2]
}

const _BaseType_name = "UnknownDecimalVarchar"

var _BaseType_index = [...]uint8{0, 7, 14, 21}

func (i BaseType) String() string {
	if i >= BaseType(len(_BaseType_index)-1) {
		return "BaseType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BaseType_name[_BaseType_index[i]:_BaseType_index[i+1]]
}
