// Code generated by mockery v1.0.0. DO NOT EDIT.

package v1

import mock "github.com/stretchr/testify/mock"

// MockSecondaryStorage is an autogenerated mock type for the SecondaryStorage type
type MockSecondaryStorage struct {
	mock.Mock
}

// LoadPage provides a mock function with given fields: _a0
func (_m *MockSecondaryStorage) LoadPage(_a0 uint32) (*Page, error) {
	ret := _m.Called(_a0)

	var r0 *Page
	if rf, ok := ret.Get(0).(func(uint32) *Page); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Page)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint32) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WritePage provides a mock function with given fields: _a0, _a1
func (_m *MockSecondaryStorage) WritePage(_a0 uint32, _a1 *Page) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint32, *Page) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
