// Code generated by "stringer -type=InsertOr"; DO NOT EDIT.

package command

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InsertOrUnknown-0]
	_ = x[InsertOrReplace-1]
	_ = x[InsertOrRollback-2]
	_ = x[InsertOrAbort-3]
	_ = x[InsertOrFail-4]
	_ = x[InsertOrIgnore-5]
}

const _InsertOr_name = "InsertOrUnknownInsertOrReplaceInsertOrRollbackInsertOrAbortInsertOrFailInsertOrIgnore"

var _InsertOr_index = [...]uint8{0, 15, 30, 46, 59, 71, 85}

func (i InsertOr) String() string {
	if i >= InsertOr(len(_InsertOr_index)-1) {
		return "InsertOr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InsertOr_name[_InsertOr_index[i]:_InsertOr_index[i+1]]
}
