// Code generated by "stringer -type=JoinType"; DO NOT EDIT.

package command

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JoinUnknown-0]
	_ = x[JoinLeft-1]
	_ = x[JoinLeftOuter-2]
	_ = x[JoinInner-3]
	_ = x[JoinCross-4]
}

const _JoinType_name = "JoinUnknownJoinLeftJoinLeftOuterJoinInnerJoinCross"

var _JoinType_index = [...]uint8{0, 11, 19, 32, 41, 50}

func (i JoinType) String() string {
	if i >= JoinType(len(_JoinType_index)-1) {
		return "JoinType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JoinType_name[_JoinType_index[i]:_JoinType_index[i+1]]
}
