// Code generated by "stringer -type=UpdateOr"; DO NOT EDIT.

package command

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UpdateOrUnknown-0]
	_ = x[UpdateOrRollback-1]
	_ = x[UpdateOrAbort-2]
	_ = x[UpdateOrReplace-3]
	_ = x[UpdateOrFail-4]
	_ = x[UpdateOrIgnore-5]
}

const _UpdateOr_name = "UpdateOrUnknownUpdateOrRollbackUpdateOrAbortUpdateOrReplaceUpdateOrFailUpdateOrIgnore"

var _UpdateOr_index = [...]uint8{0, 15, 31, 44, 59, 71, 85}

func (i UpdateOr) String() string {
	if i >= UpdateOr(len(_UpdateOr_index)-1) {
		return "UpdateOr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UpdateOr_name[_UpdateOr_index[i]:_UpdateOr_index[i+1]]
}
